### ISSUE TITLE
Database response exceeded size limit

### ISSUE THREAD

**Issue by DanSchoppe** [chanzuckerberg/aurora-data-api#1]
👋 @kislyuk! I love the library! Pretty cool how quickly you were able to add support for Aurora Data API 😄

I'm working with some geospatial data that can get fairly large. Unfortunately that means my queries can overflow the boto3 ExecuteStatement size limit:
> botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: Database response exceeded size limit
As you can imagine, limiting the number of returned records (probably via server-side cursor) would help here.

I'm new to sqlalchemy but it looks like some other database APIs have support for server-side cursors (see `stream_results` and `max_row_buffer` for [psycopg2 execution options](https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#per-statement-connection-execution-options)). 

Just curious if you have thoughts on:
- how this driver could add support for server-side cursors
- other ideas to limit the response size from Data API to combat the "response exceeded size limit" error

In the meantime, I think I'll poke around the `psycopg2` driver for inspiration. Thanks again for publishing this!

**Comment by DanSchoppe** [comment]
@kislyuk I found your cursor description in the README and some relevant logic in the source code:
> The cursor supports iteration (and automatically wraps the query in a server-side cursor and paginates it if required)

>         except self._client.exceptions.BadRequestException as e:
>            if "Please paginate your query" in str(e):
>                self._start_paginated_query(execute_statement_args)

I'll need to fetch much fewer than 1000 records at a time (default of `_start_paginated_query`) to avoid the "response exceeded size limit" error. I forked your repo and attempted to force a page size of 1:

>    def execute(self, operation, parameters=None):
>        self._iterator, self._next_page_args = None, None
>        execute_statement_args = dict(self._prepare_execute_args(operation),
>                                      includeResultMetadata=True)
>        if parameters:
>            execute_statement_args["parameters"] = self._format_parameter_set(parameters)
>        self._start_paginated_query(execute_statement_args, 1)
>        self._iterator = iter(self)

I'm inspecting the engine logs (`echo=True`) and unfortunately I'm not seeing any mention of a cursor being created or the SQL queries being limited in any way, although this is quite possibly user error.

**Comment by kislyuk** [comment]
Hi @DanSchoppe, glad you found this useful. The page size is governed by the `records_per_page` parameter here: https://github.com/chanzuckerberg/aurora-data-api/blob/d23998d56f58d5424571f5b510c54e06678e7d2d/aurora_data_api/__init__.py#L143-L150

Can you change the `records_per_page` value (default 1000) in your code and see if that helps?

Currently this parameter is not exposed to the caller. I could expose it to the caller somehow, and/or halve the parameter (binary search for the appropriate value) whenever the "Database response exceeded size limit" error appears.

This library is still very young so you're going to have to be the guinea pig for shaking out some of these issues :)

**Comment by kislyuk** [comment]
Oh and you'll need one more step: trigger the pagination behavior if the "Database response exceeded size limit" string appears in addition to "Please paginate your query":
```
    except self._client.exceptions.BadRequestException as e:
       if "Please paginate your query" in str(e) or "Database response exceeded size limit" in str(e):
           self._start_paginated_query(execute_statement_args)

**Comment by DanSchoppe** [comment]
Thanks for the prompt response, @kislyuk!

That's more or less what I attempted to do on this fork:
https://github.com/SenteraLLC/aurora-data-api/blob/599cfab2206d8e2bb4148f3c4cf9cd8394fe157a/aurora_data_api/__init__.py#L173

I must not have properly switched my local project to the forked dependency because the verbose output didn't show anything about cursors. Must have been an error on my end. I'll give it another shot and report back!

**Comment by DanSchoppe** [comment]
@kislyuk Is it possible that there is some `rowcount` logic or properties missing from the AuroraDataAPICursor? Here's a stack trace when I try to use the paginated query:
```
  File ".../sqlalchemy/engine/result.py", line 807, in rowcount
    return self.context.rowcount
  File ".../sqlalchemy/engine/default.py", line 1130, in rowcount
    return self.cursor.rowcount
AttributeError: 'AuroraDataAPICursor' object has no attribute 'rowcount'
```

I attempted to set `supports_sane_[multi_]rowcount = False` in the `sqlalchemy_aurora_data_api` repo but got the same error.
```python
class AuroraPostgresDataAPIDialect(PGDialect):
    supports_sane_rowcount = False
    supports_sane_multi_rowcount = False
```

**Comment by kislyuk** [comment]
@DanSchoppe not just possible, certain. I haven't implemented rowcount yet - and it does appear to be required by the DB API (https://www.python.org/dev/peps/pep-0249/#rowcount).

Filed #2 to track that.

**Comment by kislyuk** [comment]
@DanSchoppe I released v0.0.5 which catches the error that you encountered, automatically backs off the page size and rewinds the cursor. Let me know if that helps.

**Comment by DanSchoppe** [comment]
Awesome, thanks so much @kislyuk! I'll try it out today and report back.

**Comment by DanSchoppe** [comment]
Hi @kislyuk,

Were you able to get the cursor logic working? I'm bumping into the following exception on the `v0.0.5` tag as well as `master`:
```
INFO:sqlalchemy.engine.base.Engine:SELECT feature.id ...
FROM feature
WHERE :param_1 = feature.feature_collection_id
2019-10-23 15:59:53,424 INFO sqlalchemy.engine.base.Engine {'param_1': 21}
INFO:sqlalchemy.engine.base.Engine:{'param_1': 21}
Traceback (most recent call last):
File ".../sqlalchemy/engine/result.py", line 724, in _getter
getter = self._metadata._getter
AttributeError: 'NoneType' object has no attribute '_getter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
File ".../sqlalchemy/orm/attributes.py", line 282, in __get__
return self.impl.get(instance_state(instance), dict_)
File ".../sqlalchemy/orm/attributes.py", line 710, in get
value = self.callable_(state, passive)
File ".../sqlalchemy/orm/strategies.py", line 730, in _load_for_state
session, state, primary_key_identity, passive
File "<string>", line 1, in <lambda>
  File ".../sqlalchemy/orm/strategies.py", line 872, in _emit_lazyload
  .with_post_criteria(set_default_params)
File ".../sqlalchemy/ext/baked.py", line 531, in all
return list(self)
File ".../sqlalchemy/orm/loading.py", line 105, in instances
util.raise_from_cause(err)
File ".../sqlalchemy/util/compat.py", line 398, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File ".../sqlalchemy/util/compat.py", line 153, in reraise
raise value
File ".../sqlalchemy/orm/loading.py", line 65, in instances
for query_entity in query._entities
File ".../sqlalchemy/orm/loading.py", line 65, in <listcomp>
  for query_entity in query._entities
File ".../sqlalchemy/orm/query.py", line 4226, in row_processor
polymorphic_discriminator=self._polymorphic_discriminator,
File ".../sqlalchemy/orm/loading.py", line 405, in _instance_processor
getter = result._getter(col, False)
File ".../sqlalchemy/engine/result.py", line 726, in _getter
return self._non_result(None)
File ".../sqlalchemy/engine/result.py", line 1168, in _non_result
"This result object does not return rows. "
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
```

One more thing: I'm anticipating the cursor needing to drop all the way down to a few rows to avoid the `Database response exceeded size limit`. What are your thoughts on adding a param to the engine / session / query so the user can have input on cursor fetch size, rather than waiting for the exponential backoff?

**Comment by kislyuk** [comment]
@DanSchoppe thanks for trying this out, I'll try to reproduce this but I may have to ask you for a repro. The cursor logic works for me as demonstrated in the test cases in this and the other repo.

You're in luck with respect to your other request. Simply set the `cursor. arraysize` attribute to an integer (default 1000) after creating the cursor.

**Comment by DanSchoppe** [comment]
Thanks for the info, @kislyuk. I bumped into the error using both the sqlalchemy ORM:
```
engine = sqlalchemy.create_engine(...)
session = sessionmaker(bind=engine)()

fc_result = session.query(FeatureCollection).\
   filter(FeatureCollection.id == feature_collection_id).\
   one()
```

... and using the sqlalchemy core:
```
engine = sqlalchemy.create_engine(...)
with engine.connect() as conn:
    for result in conn.execute("select * from feature where feature.feature_collection_id = 1"):
        print(result)
```

Using the tests you referenced as inspiration, I was able to get the cursor paging to work, including the exponential backoff and the cursor.arraysize:
```
    with aurora_data_api.connect(...) as conn, conn.cursor() as cur:
        cur.execute("select * from feature where feature.feature_collection_id = 1")
        for r in cur:
            print(r)
```

Are the ORM / core supported tools? Thanks for your insight on this!

**Comment by kislyuk** [comment]
@DanSchoppe the ORM and core are supported - that's the point of this library :)

I'm still not sure how to reproduce your issue - I have similar code in the test suite, and it's working. From your error it seems like something is going on with a ResultProxy object (its _metadata attribute is not being set, but that's supposed to happen at initialization, and this library does not touch that code at all).

**Comment by DanSchoppe** [comment]
👋 @kislyuk,

Sorry for the delay. I switched gears a bit and ended up going with vanilla `sqlalchemy` + `psycopg2` rather than using the Data API. Thank you very much for the library and for the support.

I'll close this issue considering it was hard to reproduce / potentially specific to my environment.

**Comment by ludaavics** [comment]
@kislyuk Thanks for the library!
FYI i am running into the same issue as @DanSchoppe above. It took me a while to even realize what the issue was, since it's no longer obvious from the traceback.

I am on version 0.1.4

```
  Traceback (most recent call last):
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 724, in _getter
    getter = self._metadata._getter
AttributeError: 'NoneType' object has no attribute '_getter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
    db.session.query(Listing).join(Source).filter(Source.name == "seloger").all()
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3211, in all
    return list(self)
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    util.raise_from_cause(err)
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 59, in instances
    *[
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 60, in <listcomp>
    query_entity.row_processor(query, context, cursor)
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 4245, in row_processor
    _instance = loading._instance_processor(
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 407, in _instance_processor
    getter = result._getter(col, False)
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 726, in _getter
    return self._non_result(None)
  File "/Users/ltiako/.pyenv/versions/miniconda3-latest/envs/pogam/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1167, in _non_result
    raise exc.ResourceClosedError(
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
```
