### ISSUE TITLE
Django support?

### ISSUE THREAD

**Issue by mulka** [chanzuckerberg/aurora-data-api#12]
Wondering if this will work with Django. Any documentation there would be helpful.

**Comment by kislyuk** [comment]
Hi, I don't work with Django on a regular basis. This package provides DBAPI 2.0 support, so it should work with any software that is compatible with that interface. If you find any issues, please let us know.

**Comment by kislyuk** [comment]
I am closing this issue for now. PRs with documentation contributions are welcome.
