### ISSUE TITLE
Add Decimal support

### ISSUE THREAD

**Issue by 4word** [chanzuckerberg/aurora-data-api#15]
The RDS Data API has better support for numeric / decimal datatypes now, by allowing you to pass a type hint in the paramter. Doc is here: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html (search for decimal on the page)

**Comment by 4word** [comment]
I went ahead and made a PR that I think covers this https://github.com/chanzuckerberg/aurora-data-api/pull/16

**Comment by kislyuk** [comment]
This is merged and I will release it shortly after some integration testing.
