### ISSUE TITLE
ValueError exception handling for Python < 3.7

### ISSUE THREAD

**Issue by pinsleepe** [chanzuckerberg/aurora-data-api#20]
Specifically [here](https://github.com/chanzuckerberg/aurora-data-api/blob/main/aurora_data_api/__init__.py#L289). Simple change to:
`except (AttributeError, ValueError):` 
I have pull request ready.

**Comment by kislyuk** [comment]
OK thanks - please send the PR.

**Comment by vpokutytskyi** [comment]
I can reproduce similar issue with Postgresql: sometimes it can cut ending '0' for timestamps, e.g. instead of `2020-09-17 13:49:32.780180` next value `2020-09-17 13:49:32.78018` will be saved.
It causes issue with `datetime.fromisoformat()` method, it expects strings with timestamp precision = 6.

**Comment by kislyuk** [comment]
@pinsleepe can you please provide a repro for this issue? I am unable to reproduce it and I'm not sure how that line could raise a ValueError.

@vpokutytskyi it seems you are referring to a separate issue, please open a new issue and provide a repro as well.

**Comment by kislyuk** [comment]
Thanks to the work of @travisagentsync in #22, I have released v0.2.7 with a fix that we believe solves this issue. Please test and open a new issue if you see any.
