### ISSUE TITLE
Transaction error in Execute StatementDatabaseError

### ISSUE THREAD

**Issue by jshhrrsn** [chanzuckerberg/aurora-data-api#27]
Hello, 

Firstly, many  thanks for the excellent contribution 👍 

I'm seeing unpredictable transaction errors arising from the aurora_data_api during our commits and queries.

```
DatabaseError: (aurora_data_api.exceptions.DatabaseError) An error occurred (BadRequestException) when calling the ExecuteStatement operation: Transaction [...] is not found 
```

What I've tried: 

1. handling the DatabaseError in my application and trying to force the commit to execute in a new transaction as follows: 

```python

from aurora_data_api.exceptions import DatabaseError
from botocore.exceptions import ClientError

def handle_invalid_transaction_id(func):
    retries = 3

    @wraps(func)
    def inner(*args, **kwargs):
        for i in range(retries):
            try:
                return func(*args, **kwargs)
            except (DatabaseError, ClientError):
                if i != retries:
                    # The aim here is to try and force a new transaction 
                    # If an error occurs and retry
                    db.session.close()
                else:
                    raise

    return inner

```

And then in my models doing something like this:

```python
class MyModel(db.Model):
    @classmethod
    @handle_invalid_transaction_id
    def create(cls, **kwargs):
        instance = cls(**kwargs)
        db.session.add(instance)
        db.session.commit()
        db.session.close()
        return kwargs
```

Unfortunately no joy here. 

2. Turning off sleeps in Aurora-serverless

I thought perhaps the issue was due to the instance hibernating mid-transaction and so experimented with turning off the sleep as per [this blog](https://dev.to/dvddpl/how-to-deal-with-aurora-serverless-coldstarts-ml0). However, sadly the issue still persists :( 

3.  I've attempted to fine to the commit with no_autoflush, but again I'm hitting the issue. 

N.b. there's also a SO for this issue [here](https://stackoverflow.com/questions/65815257/sqlaclhemy-auroa-serverless-invalid-transaction-issue-on-commit-aurora-data-ap )

I don't know if this is a user error or an issue with the driver, but any help would be greatly appreciated as this is blocking a deployment. 

Many thanks

**Comment by jurasofish** [comment]
What's to suggest the problem is related to this library?

I'd guess you could use a debugger to intercept the calls to boto3 (e.g. here https://github.com/chanzuckerberg/aurora-data-api/blob/509cefe2645af0d9cc21449fb739a18b13410062/aurora_data_api/__init__.py#L220) and try to figure out if the issue is with the library, or if this library is simply propagating an error that's occurring at a deeper layer.

**Comment by jshhrrsn** [comment]
Just to close this off,  and in case it helps anyone else, found the issue was in the transactions that were being created by in the `cursor`.

```python 
 def cursor(self):
        if self._transaction_id is None:
            res = self._client.begin_transaction(
                database=self._dbname,
                resourceArn=self._aurora_cluster_arn,
                # schema="string", TODO
                secretArn=self._secret_arn)
            self._transaction_id = res["transactionId"]
```
 
I can't answer the _why_, but we noticed that transactions were expiring despite the fact the data successfully committed. e.g: 

request 1 - creates a bunch of transactions, write data, exits. 
request 2 - creates a bunch of transactions, some transaction id for request 1 fails, exits. 

So yeah, I don't think the issue is with the `aurora-data-api`, but somehow to do with transaction mgmt in general in aurora-serverless. In the end, we forked the repo and refactored so that everything is handled with `[ExecuteStatment](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html)` calls rather than using transactions. It's been working fine so far (note we're using SQLalchemy of transactions are handled at the ORM level anyway).
