### ISSUE TITLE
NoRegionError: You must specify a region.

### ISSUE THREAD

**Issue by khilshah** [chanzuckerberg/aurora-data-api#40]
Hi,

I get this error when I try to run your sample code specifying my cluser_arn and secret_arn:

NoRegionError: You must specify a region.

The connect function -

with aurora_data_api.connect(
    aurora_cluster_arn=cluster_arn, 
    secret_arn=secret_arn, 
    database=database) as conn:

does not allow specifying a region_name parameter like boto3.client does.

**Comment by kislyuk** [comment]
You can use the rds_data_client keyword argument to pass a custom client to the connection constructor.

**Comment by khilshah** [comment]
Oh thank you! I knew there was that parameter, just didn't know how it was worded! 

Worked a treat, much obliged :)

**Comment by morgan-young** [comment]
@somedaysuccess have you got an example of how you solves this please?

**Comment by khilshah** [comment]
@morgan-young this is how I got it to work.. left [your_parameter] where you'd need to feed in your information

rds_client = boto3.client(
    'rds-data', 
    aws_access_key_id = [your_parameter], 
    aws_secret_access_key = [your_parameter],
    region_name = [your_parameter]
    )

with aurora_data_api.connect(
    aurora_cluster_arn = [your_parameter], 
    secret_arn = [your_parameter], 
    rds_data_client = rds_client,
    database = [your_parameter]
    ) as connection:
    
    with connection.cursor() as cursor:
        
        cursor.execute(sql_query)
