### ISSUE TITLE
v0.3.0 fails on aurora postgresql json columns

### ISSUE THREAD

**Issue by sammywachtel** [chanzuckerberg/aurora-data-api#41]
Hey there,

When upgrading to 0.3.0 (and sqlalchemy-aurora-data-api 0.3.1) from 0.2.7, loading json columns starts to fail with `"the JSON object must be str, bytes or bytearray, not dict"`.

Versions:

- Python: 3.7.10
- aurora-data-api: 0.3.0
- sqlalchemy-aurora-data-api: 0.3.1
- AWS Aurora Serverless Data API for postgresql

Digging in, it seems that aurora-data-api 0.3.0 is now returning json data as a dictionary and version 0.2.7 returned a string.

The following line in __init__. _render_value(): [see line on github](https://github.com/cloud-utils/aurora-data-api/commit/c178800baf9e8372ef1f13cf911cf99d0ede4b8e#diff-dc624496abe29ae3ac49172a829f87d9254dc5ff1094d852805234beb96ee2eeR293) converts the json string to a dict with the code `json.loads(scalar_value)`.

Then, sqlalchemy sql.sqltypes.py tries to re-load the data as a dictionary in a result_processor() method: [see method on github](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_2/lib/sqlalchemy/sql/sqltypes.py#L2568), but you can't run `json.loads` on a dict or you get the above error.

Using the previous version for now, but wanted to submit this issue to log it.

Also, I notice that there is a related issue in the sqlalchemy-aurora-data-api project, but I think the issue belongs in the aurora-data-api project. ([sqlalchemy-aurora-data-api issue](https://github.com/cloud-utils/sqlalchemy-aurora-data-api/issues/33))

Thanks!

**Comment by kislyuk** [comment]
Fixed in v0.3.1.

Thank you for reporting.

**Comment by sammywachtel** [comment]
@kislyuk 
Tested and it works! Thanks so much for your work on this and on the library in general!
Sam
