### ISSUE TITLE
Example on Insert Query with SQL parameterized Statement

### ISSUE THREAD

**Issue by guneshsji** [chanzuckerberg/aurora-data-api#42]
Hey there @kislyuk ,
I was using your library and I really liked it and you have done an amazing job by building it. Thank you for that,

The reason I created this issue is because, I was trying to run an insert query with Sql parameterized statement instead of an f string. But I was not able to find any example on this topic in this library docs.

So, any example in the readme about insert query using Sql parameterized statement to avoid sql injection will be helpful.

I am using Aurora Mysql and aws python Lambda.
Regards.

**Comment by kislyuk** [comment]
Hello, and thank you for your interest in aurora-data-api.

General examples of SQL parameter usage in Python DB-API are outside the scope of this library's documentation. Please see general Python database API help resources for examples of this.
