### ISSUE TITLE
Using Tuples in cursor.excecutemany does not work with aurora_data_api.connect()

### ISSUE THREAD

**Issue by yuvaljacob** [chanzuckerberg/aurora-data-api#45]
I have noticed that when using the aurora_data_api, when using the cursor.executemany method for a MySQL DB, I cannot use a list of Tuples, only a list of dicts is processed correctly, while the "official" MySQL Python docs give an example of using a Tuple and not a dict.

When I try to use a list of Tuples with cursor.excecutemany, like seen below, I get an error message regarding Tuples:

``` sql = """
            INSERT INTO aurora_data_api_test
            (name, doc, num, ts)
            VALUES (%s, %s, %s, %s)
            """
            
            data = [(f"name-{i}", f"doc-{i}", "5.0", "2020-09-17 13:49:32.780180") for i in range(2048)]
            
            response = cursor.executemany(sql, data)
```

`[ERROR] AttributeError: 'tuple' object has no attribute 'items'`

I believe that it is related to this part in your __init__.py file, which expects to get a dict:

  ```
  def _format_parameter_set(self, parameters):
        return [self.prepare_param(k, v) for k, v in parameters.items()]
```

Can you please help me with understanding this gap? The only way that it seems to work with auroro_data_api, is if I do this instead:

```
sql = """
            INSERT INTO aurora_data_api_test
            (name, doc, num, ts)
            VALUES (:name, :doc, :num, :ts)
            """

            response = cursor.executemany(sql, [
                {
                    "name": f"name-{i}",
                    "doc": f"doc-{i}",
                    "num": "5.0",
                    "ts": "2020-09-17 13:49:32.780180"
                } for i in range(2048)]
            )

```
If I run the code above and use my local docker image with the latest MySQL image, I get this error:

`pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':name, :doc, :num, :ts)' at line 3")
`

**Comment by kislyuk** [comment]
Thanks for reporting - this is just to acknowledge that this seems like an issue in the mysql implementation. I'll take a look when I get a chance to spin up a test RDS instance again.

**Comment by yuvaljacob** [comment]
Hello,

Yes, this is related to using cursor.fetchmany which does not support the
standard implementation which uses Tuples.

Please copy ***@***.*** in your updates
(copied here as well).

Your assistance here is highly appreciated.

Thanks,
Yuval.

**Comment by kislyuk** [comment]
Hi Yuval, can you please adjust your tone? This is a collaborative open source project. We work on it for free in our spare time, and we respect each other's time and effort. While I certainly appreciate you pointing out a bug, I will not be copying anyone on anything, nor is it appropriate to request any such thing from the community in the project's issue tracker. Furthermore, if your business depends on this project, the ethical course of action for you would be to donate to the developers of the project.

**Comment by yuvaljacob** [comment]
Hi,

This is just my work email address, it's not any other person's email
address.

I just kindly asked to copy this address as well so it would be easier for
me to collaborate with you, sorry for the wrong message I did not intend to
offend anyone.

Yuval.

**Comment by kislyuk** [comment]
OK, sounds good. Unfortunately there isn't any way for me to control who the email notifications from GitHub go to; you can do that by adding your work email to your GitHub account and configuring the notifications.

**Comment by kislyuk** [comment]
RDS Data API does not support array parameters. Added an error message to make this explicit.
