### ISSUE TITLE
Feature request: inject existing AWS session to aurora_data_api instead of opening a new session

### ISSUE THREAD

**Issue by yuvaljacob** [chanzuckerberg/aurora-data-api#46]
We are interested to know if there is an option, or a plan to introduce an option to inject an existing session with AWS into aurora_data_api.connect(), instead of creating an additional one with your service, I will be glad to hear your thoughts about this matter.

**Comment by bruceadams** [comment]
I this related to #43 ?

**Comment by bruceadams** [comment]
I cannot find any uses of a boto3 session in the `aurora_data_api` code. What you can do is inject is a boto3 client for `rds-data` (and #43 gives a reason you might want to).

**Comment by kislyuk** [comment]
As @bruceadams said, this functionality is supported by way of the `rds_data_client` keyword argument in the client constructor.

**Comment by yuvaljacob** [comment]
Hello,

Thank you for your response, we will review this internally and will let
you know if we have any comments on the feature request.

Yuval.
