### ISSUE TITLE
Thanks & PyPi name offer

### ISSUE THREAD

**Issue by dschep** [chanzuckerberg/aurora-data-api#9]
Hey @chanzuckerberg, thanks for this (and the sqlalchemy) package! I made an earlier attempt at this same functionality but never got a chance to finish: https://github.com/dschep/rdsdataapi

I'm happy to give you control of the package `rdsdataapi` on PyPi if you're interested in it.

**Comment by kislyuk** [comment]
Thank you for your kind words and your package namespace offer. We are good with this name for now, but we appreciate the thought.
